baseline model docker image
Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra pull request #6
Opened 2023-06-22 21:52 UTC by mdsage1

Added Dockerfile and base_model script.
Included TSV files requred to build the model.

2023-06-22 21:59 UTC, mdsage1 reviewed
Docker Image has been pushed to RARE-X live.

2023-06-23 21:26 UTC, vpchung requested changes
Great start!  Couple comments.

2023-06-23 21:26 UTC, vpchung commented on baseline/Dockerfile
> +RUN chmod +x base_model.py
We want the container to act as an executable, so we should add an ENTRYPOINT so that base_model.py runs when the container starts. Something like [this](https://github.com/Sage-Bionetworks-Challenges/sample-model-templates/blob/406dc4c89831f0f17d53d6e6ceeb3a47f07a308d/python/Dockerfile#L24).

2023-06-23 21:26 UTC, vpchung commented on baseline/base_model.py
> +training_features = pd.read_csv('baseline/training_features.tsv',sep='\t')
In the [submission tutorial](https://www.synapse.org/#!Synapse:syn51198356/wiki/621448), we instruct participants that all input data will be mounted in a folder called `/input`.  So, we could either:

1. update this filepath so that it looks at the `/input` directory
2. update the submission tutorial instructions to specify `/baseline` instead of `/input`

2023-06-23 21:26 UTC, vpchung commented on baseline/base_model.py
> +resultsdf.to_csv('output/predictions.tsv',sep='\t',index=False)
Similar to above ^, the submission tutorial instructs participants to print their predictions file into the `/output` directory.

2023-06-23 21:26 UTC, vpchung commented on baseline/base_model.py
> +training_features = pd.read_csv('baseline/training_features.tsv',sep='\t')
Nit: instead of `pd.read_csv(..., sep="\t")`, you can use `pd.read_table(...)`.

They both behave exactly the same, except `read_table` uses `"\t"` as the default separator!

2023-06-23 21:40 UTC, mdsage1 commented on baseline/Dockerfile
> +RUN chmod +x base_model.py
Added the entrypoint

2023-06-23 21:43 UTC, mdsage1 commented on baseline/base_model.py
> +resultsdf.to_csv('output/predictions.tsv',sep='\t',index=False)
Updated the output directory

2023-06-23 21:52 UTC, vpchung approved these changes

2023-06-23 21:52 UTC, vpchung commented on baseline/base_model.py
> +resultsdf = pd.DataFrame({'Participant_ID':testing_features['Participant_ID'].values,'Disease Name':results})
Uhh, where my commas at?! 🤣

2023-06-27 19:09 UTC, merged